replicaCount: 2

image:
  repository: comrry/devops
  tag: ""
  pullPolicy: IfNotPresent

metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/USERNAME/app
    argocd-image-updater.argoproj.io/update-strategy: latest
    
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  APP_PORT: "8080"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASS: "password"
  DB_NAME: "appdb"
  REDIS_ADDR: "redis-master:6379"
