replicaCount: 2

migration:
  enabled: true
  jobName: "app-migration"

image:
  repository: docker.io/comrry/devops
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

db:
  user: "app"
  name: "appdb"
  instanceConnectionName: "storied-reserve-473208-t1:asia-northeast3:devops-postgres"

projectId: "storied-reserve-473208-t1"

env:
  APP_PORT: "8080"
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_USER: "app"
  DB_NAME: "appdb"
  DB_PASS_FROM_SECRET: "app-db-secret"

  REDIS_ADDR: "redis-master.default.svc.cluster.local:6379"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi
