apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/comrry/devops
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/jyong0/devops-portfolio.git
    targetRevision: main
    path: charts/app

    helm:
      releaseName: app
      values: |
        image:
          repository: docker.io/comrry/devops
          tag: "latest"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
