# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: app-backendconfig
# spec:
#   healthCheck:
#     checkIntervalSec: 5
#     timeoutSec: 5
#     healthyThreshold: 2
#     unhealthyThreshold: 2
#     type: HTTP
#     requestPath: /healthz
#     port: 8080
